#+title: jthulhu' machines configuration
#+author: jthulhu
#+description: An overview and explanation of my configuration.
#+language: en
#+options: toc:2 p:t

* General overview
This repository is a [[https://nixos.wiki/wiki/Flakes][flake]], meaning it is meant to be used with the [[https://nixos.org/][nix]] package manager.
This flake provides the configuration for my personal machines, including both the system
settings and the per-user settings.

* Bootstrap
To bootstrap an installation, perform a regular nixos installation, using the current repository
as source.  Then, you need:
- the GPG key
- the SSH bootstrap key
using which you can access the password store, and decrypt the passwords.  This, in turn, will
allow you to use the normal SSH key.  You can then stop using the SSH bootstrap key.

** Generating secrets
Some parts of the configuration require secrets to be available in plain text at some point.
This is done by encrypting the secrets with =rage=, then require that a suitable key is availble on
the system.

*** Creating new secrets
To create a new secret, you must start by editing the =secrets/secrets.nix= file.  You must add a
key, which will happen to be the name of the file containing to the secret, to the struct.  The
corresponding value must contain a =publicKeys= list of keys used to encrypt the secret, meaning
that the corresponding private keys will be able to decipher the secret.  It must also contain a
=script= field which will be executed to populate the secrets.  It must produce to stdout the
content of the file that should be accessible.  The script will be run once, then the encrypted
secrets will be added to the repository.

*** Producing the ciphered secrets
You have to be in the =secrets/= sub-directory, then run
#+begin_src sh
  mk-secrets
#+end_src
Then, commit any changes (which will be located in the =secrets/= directory).

*** Storing the keys on the system
The keys should be store at =/var/lib/rage/<hostname>.priv=.  Make sure they have suitable
permissions (ie. only =root= can access).

* Encrypting directories
Encrypting directories is currently done with =fscrypt=.  First, you need to ensure that the
filesystem supports native encryption.  Currently, =ext4=, =f2fs= and a few others feature native
encryption.  To enable encryption, run the following
#+begin_src sh
  sudo tune2fs -O encrypt /dev/<partition>
#+end_src
You can run =fscrypt status= to see if a filesystem supports encryption, and if encrypt is
enabled.  Once this has been done, you have to setup encryption on that partition.
#+begin_src sh
  sudo fscrypt setup [mountpoint]
#+end_src
This asks if the management of policies and protectors can be managed by every user.  Answer yes.
Then, you need to create an empty directory, and encrypt it using =fscrypt encrypt <directory>=.
Then, the directory can be (un)locked using =fscrypt lock <directory>= and ~fscrypt unlock
<directory>~.  Note that if you used the pam protector, the directory will be unlocked on login.
* Secrets
This repository contains personal information that is redacted, using =git-crypt=.  No password is
stored this way, but personal information such as private emails, calendar accounts and stuff
like that.

To redact the content of a file, including it in the [[file:.gitattributes][gitattributes]] file, indicating
#+begin_src
  pattern filter=git-crypt diff=git-crypt
#+end_src
*Warning!* the =.gitattributes= file itself should never be crypted, or there will be problems.

Note that it should always be possible to build the system even without decrypting the redacted
files.  To achieve that, you should always include a /tag/ file with a dummy content, that is
included in the redacted files, and to check whether its content is the dummy content you expect,
in which case you are allowed to load all redacted files.
* ~evscript~ setuid
~evscript~ requires its binary to have privileged access to the filesystem.  To have it work, we
need some additional work
#+begin_src nix
  security.wrappers.evscript = {
    setuid = true;
    owner = "root";
    group = "root";
    source = "${pkgs.evscript}/bin/evscript";
  };
#+end_src
* Which-key popup
Shortcuts using sway have a which-key like popup that shows up.  It is implemented independently
of the actual shortcuts (the shortcuts are processed by sway, whereas which-key is an independent
service that just listens to sway for mode changes).

In particular, any change to the shortcuts should be reflected in [[file:home/eww/default.nix::6][this file]]
* Reset author of all commits
To reset the author information of all commits in a repository, run
#+begin_src bash
  git -c rebase.instructionFormat='%s%nexec GIT_COMMITTER_DATE="%cD" GIT_AUTHOR_DATE="%aD" git commit --amend --no-edit --reset-author' rebase -f --root
#+end_src
This will preserve the original date of the commit.
*Warning*: This will reset the commit hashes, hence it will destroy the history, meaning that you
will have to ~git push --force~, and be annoying for anyone else working on the repository.
